feat: Credential Service billing Apis
cheqd/credential-service-portal pull request #12
Opened 2024-03-14 06:28 UTC by benyam7

2024-03-14 06:28 UTC, ankurdotb commented
Task linked: [DEV-3671 Backend: Integrate Stripe payments into CaaS portal to provide access to different tiers](https://app.clickup.com/t/6600954/DEV-3671)

2024-03-23 23:16 UTC, lampkin-diet commented on src/lib/api/credentialServiceBilling.ts
> +			scope: 'all'
@benyam7 I implemented the required check on CaaS side and let's introduce here scopes instead of granting all the permissions.

2024-04-11 10:40 UTC, benyam7 commented
> @benyam7 here is some UI changes we might need:
> 
> 1. ![SCR-20240402-opia](https://private-user-images.githubusercontent.com/68041753/318756304-45dd38a8-6961-46ee-9df7-77534e7d4f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjQyMjYsIm5iZiI6MTcxMjgyMzkyNiwicGF0aCI6Ii82ODA0MTc1My8zMTg3NTYzMDQtNDVkZDM4YTgtNjk2MS00NmVlLTlkZjctNzc1MzRlN2Q0ZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzYTk2ZTIwMDcyZjMyYWUzMDQ1NDk2Njc2MzY2NzhjYzgyZDM2YTAwNWUzNGFlZjIxNmNiZGE1YTE0NjQyOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQEmFklGNVrUNJupLq2mgrvm215hx-2goEefMAe8CuY)
> 2. ![SCR-20240402-oqms](https://private-user-images.githubusercontent.com/68041753/318756555-143a2507-41e2-4d82-b33a-4cbbff9143bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjQyMjYsIm5iZiI6MTcxMjgyMzkyNiwicGF0aCI6Ii82ODA0MTc1My8zMTg3NTY1NTUtMTQzYTI1MDctNDFlMi00ZDgyLWIzM2EtNGNiYmZmOTE0M2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNjFmNDNkYzc1NjY5NjVlYmI1ZjRjYWY5MTM4ZTQxNTQwMmYxMzI5YjQ3ODU4ZTcyNWNiZGFhZjRlZWQwZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9fUX_sSmV-V-VNauhpaqhqSqdKNAl3sWHL3oWezOOTU)
> 3. ![SCR-20240402-oqyn](https://private-user-images.githubusercontent.com/68041753/318756610-34b30027-bd8a-4c74-832e-88a136a220f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjQyMjYsIm5iZiI6MTcxMjgyMzkyNiwicGF0aCI6Ii82ODA0MTc1My8zMTg3NTY2MTAtMzRiMzAwMjctYmQ4YS00Yzc0LTgzMmUtODhhMTM2YTIyMGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA4MjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YTQ0YWM0ODYwZmUyMDQxMjZmY2UxY2RjNWFhMzQ3NGZhYzZlNGFhZjJlYWIzODhkODJkNDU3YWE0OTI2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h2W9H169rirEVvEfz4iVJm0CqDY7QzEFCgMuywgQzU0)
> 
> on number 3, I think we should also remove the grey tint and keep it white with subtle borders and shadows to separate fro m bg like original PR had.

@guacamole I've resolved the UI changes.

2024-04-16 12:33 UTC, ankurdotb requested changes
For the comments here that say "Look this up from Stripe", there are two options:

1. Get the Credential Service to query this from Stripe and pass it back as part of the response it gives on what plans are available, what the current plan is, whether it's within trial or not etc. (Since there's no Stripe API keys set, this seems to be the model we have adopted in this frontend, so this is preferred option unless someone disagrees.)
2. Fetch it directly from Stripe API from this FE (but then you need to be very clear on which bits are queried from FE vs BE and why you're keeping that difference).

2024-04-16 12:33 UTC, ankurdotb commented on example.env
> +PUBLIC_STRIPE_UPDATE_SUBSCRIPTION_RETURN_URL="http://localhost:3002/home"
Maybe just define a base endpoint and then route/deal with where create vs update vs cancel return to, instead of 3 separate URLs?

2024-04-16 12:33 UTC, ankurdotb commented on example.env
> +PUBLIC_NODE_ENV='staging'
Necessary? (Set automatically by Cloudflare Pages, as far as I understand, but might be needed for local)

2024-04-16 12:33 UTC, ankurdotb commented on src/lib/api/credentialServiceBilling.ts
> +					: 'admin:subscription:create:testnet admin:subscription:get:testnet admin:subscription:update:testnet admin:product:list:testnet admin:subscription:list:testnet'
This is a question for @lampkin-diet: do we need to subdivide the `subscription` scope further with `mainnet` and `testnet`? I'm not sure whether we do, since "subscription" is a property of the account overall, unlike DIDs, credentials etc. I can't think of the use case in which this sub-division is needed, but maybe I'm missing something.

If the permission scopes need to be changed in LogTo, then they'd change here as well. Otherwise, if they remain as-is then this remains as-is.

2024-04-16 12:33 UTC, ankurdotb commented on src/lib/api/subscriptions.ts
> +			trialPeriodDays: 14
Length of trial period is/should be controlled at Stripe, so don't assume this will be set by environment variable here. Instead, fetch the details of the plans in Stripe and then display them. The only "unique" case would be the custom plan, which wouldn't be created as a public plan in Stripe at all.

2024-04-16 12:33 UTC, ankurdotb commented on src/lib/client/constants.ts
> +export const CACHED_PRODUCTS_SESSION = 'cachedProducts';
Some of the ones read from .ENV may go here, if not needed to be settable via ENV.

2024-04-16 12:33 UTC, ankurdotb commented on src/lib/client/constants.ts
> +export const CACHED_PRODUCTS_SESSION = 'cachedProducts';
Also I'm not sure about the point of this variable per se. Can it have any value other than `cachedProducts`?

2024-04-16 12:33 UTC, ankurdotb commented on src/lib/client/helpers.ts
> +};
You should fetch this data from Stripe to determine how many days into the trial and how many are left. :) Otherwise, if this is running client-side then just setting the system clock to a different time would give a different result here. This is before we even get into timezone funkiness.

If this is running server-side only, that's a _bit_ better but you could still run into edge cases, since a Pages/Worker could be provisioned in any of Cloudflare's data centres across the world (theoretically, the one closest to the user). So on _most_ occasions during the trial period this will be roughly fine, but on/around the last day you could run into weird edge cases where say the time/date in Stripe is on UTC while the user is in Australia (and in a different day then Stripe). I'm not sure whether this code above accounts for timezones, but this is a very good reason to rely on Stripe to decide in/out of trial. The other scenario is if the plan is upgraded to a paid plan before the trial ends, which would also run into subtle edge cases.

2024-04-16 12:33 UTC, ankurdotb commented on src/lib/components/BillingPlanCard.svelte
> +	export let currency: string = 'gbp'; // we defaulting to gbp
Default to the default currency in the Stripe plan

2024-04-16 12:33 UTC, ankurdotb commented on src/lib/components/CurrentPlanCard.svelte
> +		{#if trialDaysLeft && trialDaysLeft > 1}
And if they are actual in a trial (since they can upgrade out of a trial any time)

2024-04-16 12:33 UTC, ankurdotb commented on src/routes/(app)/billing/+page.svelte
> +			/>
Either put in constants.ts or directly here

2024-04-16 12:33 UTC, ankurdotb commented on vite.config.ts
> +		port: 3002
Might have been changed to accommodate Stripe but is this the value we wanna keep long-term?

2024-04-16 13:29 UTC, lampkin-diet commented on src/lib/api/subscriptions.ts
> +			trialPeriodDays: 14
If you create a subscription using Stripe dashboard - yes, you can specify triel period there. But If you are using stripe checkout as we do - you need to specify trial period in days when creating a session.
Here are the docs:
https://docs.stripe.com/api/checkout/sessions/create#create_checkout_session-subscription_data

Please take into account that we are not using `stripe.supscription` functionality cause don't wanna to replicate Stripe UI

2024-04-16 13:29 UTC, lampkin-diet commented on src/lib/client/helpers.ts
> +};
As I remember, Stripe returns `trialEnd` timestamp, not days are left. I think this functions helps to calculate what days are left. But I agree if we are able to get not CloudFlare time but user's browser maybe that will be helpful?

2024-04-16 13:29 UTC, lampkin-diet commented on vite.config.ts
> +		port: 3002
I think this one should be configurable.

2024-04-16 15:16 UTC, ankurdotb commented on src/lib/api/credentialServiceBilling.ts
> +					: 'admin:subscription:create:testnet admin:subscription:get:testnet admin:subscription:update:testnet admin:product:list:testnet admin:subscription:list:testnet'
Okay cool! So for these scopes, I'd recommend dropping the mainnet/testnet.

Cloudflare will automatically have the node_env as "production" in prod and "development" in staging, IIRC. I don't remember if they actually populate it in NODE_ENV or if it's in a custom variable, but I believe it's the former. Based on whether it's "production" or "development", you could choose live or test for Stripe modes.

If you want to do something else on local vs on Cloudflare, there's apparently a variable called `CF_PAGES` that can be used as a boolean for this: https://developers.cloudflare.com/pages/configuration/build-configuration/#environment-variables

2024-04-16 15:18 UTC, ankurdotb commented on src/lib/api/subscriptions.ts
> +			trialPeriodDays: 14
Okay good to know. But wouldn't they come through from a pricing table on the cheqd.io website, which does include the number of trial days? I can't think of a scenario where the start of the trial originates from THIS front-end app, but I do get your point.

Let's make it a constant that is set to a default value like 30 days OR reads from an environment variable.

2024-04-16 15:20 UTC, ankurdotb commented on src/lib/client/helpers.ts
> +};
I would calculate the time on server-side, normalise it to UTC as well as Stripe's timestamp to UTC, calculate days remaining and send that back to the frontend.

2024-04-16 15:20 UTC, ankurdotb commented on src/hooks.server.ts
> +				scope: 'all'
Agreed on this!

2024-04-16 16:29 UTC, benyam7 commented on example.env
> +PUBLIC_NODE_ENV='staging'
Okay, didn't know that. 👍🏾  Will remove.

2024-04-16 16:46 UTC, benyam7 commented on src/lib/client/helpers.ts
> +};
We verify subscription status using the trialEnd timestamp from Stripe. While users could alter their local time, the plan will still end on Stripe's side. However, for a smoother UI experience, backend calculation is preferable.

2024-04-16 16:49 UTC, benyam7 commented on src/lib/components/BillingPlanCard.svelte
> +	export let currency: string = 'gbp'; // we defaulting to gbp
we are, but this occurs before we receive a response from Stripe.

2024-04-16 16:50 UTC, benyam7 commented on vite.config.ts
> +		port: 3002
yep, i will make it configurable.

2024-04-17 08:04 UTC, benyam7 commented on src/hooks.server.ts
> +				scope: 'all'
@ankurdotb @lampkin-diet This M2M token is solely for accessing Logto upstream APIs to list user scopes, not for the credential service. I'm unsure if we have specific scopes set for that, but this is our approach in both creds-app and studio.

2024-04-17 08:06 UTC, benyam7 commented on src/lib/types/schemas/subscription.schema.ts
> +	idempotencyKey: z.string().optional(),
@lampkin-diet  you mean `idempotencyKey` or are you referring the whole schema?

2024-04-17 08:08 UTC, benyam7 commented on src/routes/api/billing/products/+server.ts
> +	if (!isAuthorized(locals, 'admin:product:list:mainnet', 'admin:product:list:testnet')) {
resolved.

2024-04-17 08:20 UTC, benyam7 commented on example.env
> +PUBLIC_STRIPE_UPDATE_SUBSCRIPTION_RETURN_URL="http://localhost:3002/home"
We have three separate URLs for flexibility in adjusting return URLs for three scenarios:
- Subscription creation
- Subscription cancellation
- Subscription updates

If following your suggestion, it loses the sole purpose.

2024-04-17 09:01 UTC, benyam7 commented on src/routes/(app)/billing/+page.server.ts
> +		const idToken = await locals.idToken;
Yep, I am thinking to log the user out if idToken has expired.

2024-04-17 09:28 UTC, benyam7 commented on src/lib/api/subscriptions.ts
> +			trialPeriodDays: 14
resolved

2024-04-17 09:29 UTC, benyam7 commented on src/lib/api/credentialServiceBilling.ts
> +					: 'admin:subscription:create:testnet admin:subscription:get:testnet admin:subscription:update:testnet admin:product:list:testnet admin:subscription:list:testnet'
resolved on client-side.

2024-04-17 09:33 UTC, benyam7 commented on src/routes/(app)/billing/+page.svelte
> +			/>
resolved.

2024-04-17 09:57 UTC, benyam7 commented on src/lib/api/credentialServiceBilling.ts
> +					? 'admin:subscription:create:mainnet admin:subscription:get:mainnet admin:subscription:update:mainnet admin:product:list:mainnet admin:subscription:list:mainnet'
Leaving this as is per our discussion today.

2024-04-17 10:44 UTC, benyam7 commented on vite.config.ts
> +		port: 3002
we cannot import envs in vite.config.ts. Here so, defaulting to 3000.

2024-04-17 11:28 UTC, benyam7 commented on src/lib/components/CurrentPlanCard.svelte
> +		{#if trialDaysLeft && trialDaysLeft > 1}
Added a check that checks, if the plan is not "Credential Service - Free Plan"

2024-04-17 16:53 UTC, ankurdotb commented on example.env
> +PUBLIC_STRIPE_UPDATE_SUBSCRIPTION_RETURN_URL="http://localhost:3002/home"
Maybe I'm misunderstanding it, but are the actual return URLs wildly different? Can you give me examples of what they actually would be? (I'd imagine they are all same base URL + some consistent path, no? Or is it something else?)

2024-04-17 16:53 UTC, ankurdotb commented on src/hooks.server.ts
> +				scope: 'all'
Ah thanks for clarifying. Not sure if that's just a legacy decision/way of doing things in creds-app/studio and there's a better way to do this (what do we do in credential service, @lampkin-diet?)

2024-04-17 16:53 UTC, ankurdotb commented on src/lib/client/constants.ts
> +export const CACHED_PRODUCTS_SESSION = 'cachedProducts';
So the static, literal string `cachedProducts` is a unique session key? That seems...off? Should it not be something unique?

2024-04-17 16:53 UTC, ankurdotb commented on src/lib/components/BillingPlanCard.svelte
> +	export let currency: string = 'gbp'; // we defaulting to gbp
Then make it USD

2024-04-18 12:14 UTC, ankurdotb requested changes
- Lots of unresolved comments: I unresolved many that had been marked as resolved. In general, let reviewers accept something as resolved, especially if it's a discussion/open-ended question. Only mark as resolved yourself if it's a very specific bug/issue/code change that's very obvious to understand as fixed/changed.
- Minor copyedits for spelling and text styling issues still to be resolved. (E.g., text says "Creating Api key" instead of "Creating API Key" at one point.)

2024-04-18 12:14 UTC, ankurdotb commented on src/lib/client/helpers.ts
> +};
Use similar technique as what's used in credential service, rather than this?

2024-04-18 12:34 UTC, benyam7 commented on example.env
> +PUBLIC_STRIPE_UPDATE_SUBSCRIPTION_RETURN_URL="http://localhost:3002/home"
@ankurdotb, same base URL. I've set up 3 separate URLs stored in environment variables: one for when subscription creation succeeds, another for subscription update success, and the third for when a user cancels their subscription. If I only store the base URL in an environment variable, I'll be restricted to modifying just that variable.

2024-04-18 12:35 UTC, benyam7 commented on example.env
> +PUBLIC_STRIPE_UPDATE_SUBSCRIPTION_RETURN_URL="http://localhost:3002/home"
if you think this is over-engineering i can remove it.

2024-04-18 12:37 UTC, benyam7 commented on src/lib/client/constants.ts
> +export const CACHED_PRODUCTS_SESSION = 'cachedProducts';
yep, I don't think the name for the key is an issue here. If you have any suggestions for a different name, feel free to share them.

2024-04-18 13:09 UTC, benyam7 commented on src/hooks.server.ts
> +				scope: 'all'
@ankurdotb  I've informed  @lampkin-diet during yesterday's call, and he confirmed it was good to proceed.

2024-04-18 13:32 UTC, ankurdotb commented on example.env
> +PUBLIC_STRIPE_UPDATE_SUBSCRIPTION_RETURN_URL="http://localhost:3002/home"
https://developers.cloudflare.com/pages/configuration/build-configuration/#environment-variables

2024-04-18 13:38 UTC, ankurdotb commented on src/lib/client/constants.ts
> +export const CACHED_PRODUCTS_SESSION = 'cachedProducts';
See if you can expire the cached products after 1 day from session storage, so that whether the cached value is expired or not is independent of what the logout/login duration is.

2024-04-18 13:46 UTC, ankurdotb commented on src/lib/components/CurrentPlanCard.svelte
> +		{#if trialDaysLeft && trialDaysLeft > 1}
Ignore the free plan, this won't exist. We're gonna force people to upgrade after 30 days. But whether or not we have a free plan, we shouldn't harcode this logic here because we might want to play around on Stripe to check whether we have free plan, or a forced upgrade after trial. Instead, check if the user _is_ in a trial, and if yes, then show remaining days.

Also, @lampkin-diet had a good point: the comparison of `trialDaysLeft > 1` will not work on the last day of the trial, even though it _should_ show something.

And if the trial _has_ ended, you should show a different message: not "your trial ends in X days", but "Your trial ended on <DATE>. Upgrade now for continued access" (i.e., prompt the user to fix the issue, you can even show a link or button if there's no existing button that allows them to change this already)

2024-04-18 13:55 UTC, ankurdotb commented on src/lib/components/CurrentPlanCard.svelte
> +		{#if trialDaysLeft && trialDaysLeft > 1}
for within trial, make it "Your trial ends in X days on `DATE`. (similar upgrade now CTA button or link)"

2024-04-18 22:37 UTC, benyam7 commented on src/lib/components/CurrentPlanCard.svelte
> +		{#if trialDaysLeft && trialDaysLeft > 1}
@ankurdotb  Consider this scenario, user signs up, subscribes to a plan. Then you will see "Your trial ends in 30 days". If you update your plan, your remaining trial days will be removed.(because of our current implementation). Showing, CTA "Upgrade now" will be not cool as user has already subscribed to a plan. Let me know your call on this.

2024-04-18 22:38 UTC, benyam7 commented on src/lib/components/CurrentPlanCard.svelte
> +		{#if trialDaysLeft && trialDaysLeft > 1}
You can also test the flow, i've pushed the change.

2024-04-19 10:20 UTC, ankurdotb approved these changes

2024-04-19 10:20 UTC, merged